[settings]
root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/main.go"
include = ["cmd", "internal", "pkg", "go.mod", "go.sum"]
exclude = []
log = "air_errors.log"
delay = 1000

[log]
time = true

[color]
main = "magenta"

[misc]
clean_on_exit = true
