version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rafa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"  # Porta AMQP
      - "15672:15672" # Interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

  # n8n:
  #   image: n8nio/n8n:latest
  #   restart: unless-stopped
  #   environment:
  #     - DB_TYPE=postgresdb
  #     - DB_POSTGRESDB_HOST=postgres
  #     - DB_POSTGRESDB_PORT=5432
  #     - DB_POSTGRESDB_DATABASE=n8n
  #     - DB_POSTGRESDB_USER=n8n
  #     - DB_POSTGRESDB_PASSWORD=0123
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=admin
  #     - N8N_BASIC_AUTH_PASSWORD=adminpassword
  #     - N8N_HOST=localhost
  #     - N8N_PORT=5678
  #     - WEBHOOK_URL=http://localhost:5678/
  #     - GENERIC_TIMEZONE=America/Sao_Paulo
  #   ports:
  #     - "5678:5678"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data:
  rabbitmq_data: