// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-go/pkg/ent/category"
	"backend-go/pkg/ent/debt"
	"backend-go/pkg/ent/invoice"
	"backend-go/pkg/ent/paymentstatus"
	"backend-go/pkg/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[3].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[4].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	debtFields := schema.Debt{}.Fields()
	_ = debtFields
	// debtDescCreatedAt is the schema descriptor for created_at field.
	debtDescCreatedAt := debtFields[8].Descriptor()
	// debt.DefaultCreatedAt holds the default value on creation for the created_at field.
	debt.DefaultCreatedAt = debtDescCreatedAt.Default.(func() time.Time)
	// debtDescUpdatedAt is the schema descriptor for updated_at field.
	debtDescUpdatedAt := debtFields[9].Descriptor()
	// debt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	debt.DefaultUpdatedAt = debtDescUpdatedAt.Default.(func() time.Time)
	// debt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	debt.UpdateDefaultUpdatedAt = debtDescUpdatedAt.UpdateDefault.(func() time.Time)
	// debtDescID is the schema descriptor for id field.
	debtDescID := debtFields[0].Descriptor()
	// debt.DefaultID holds the default value on creation for the id field.
	debt.DefaultID = debtDescID.Default.(func() uuid.UUID)
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescCreatedAt is the schema descriptor for created_at field.
	invoiceDescCreatedAt := invoiceFields[6].Descriptor()
	// invoice.DefaultCreatedAt holds the default value on creation for the created_at field.
	invoice.DefaultCreatedAt = invoiceDescCreatedAt.Default.(func() time.Time)
	// invoiceDescUpdatedAt is the schema descriptor for updated_at field.
	invoiceDescUpdatedAt := invoiceFields[7].Descriptor()
	// invoice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invoice.DefaultUpdatedAt = invoiceDescUpdatedAt.Default.(func() time.Time)
	// invoice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invoice.UpdateDefaultUpdatedAt = invoiceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// invoiceDescID is the schema descriptor for id field.
	invoiceDescID := invoiceFields[0].Descriptor()
	// invoice.DefaultID holds the default value on creation for the id field.
	invoice.DefaultID = invoiceDescID.Default.(func() uuid.UUID)
	paymentstatusFields := schema.PaymentStatus{}.Fields()
	_ = paymentstatusFields
	// paymentstatusDescCreatedAt is the schema descriptor for created_at field.
	paymentstatusDescCreatedAt := paymentstatusFields[3].Descriptor()
	// paymentstatus.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentstatus.DefaultCreatedAt = paymentstatusDescCreatedAt.Default.(func() time.Time)
	// paymentstatusDescUpdatedAt is the schema descriptor for updated_at field.
	paymentstatusDescUpdatedAt := paymentstatusFields[4].Descriptor()
	// paymentstatus.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentstatus.DefaultUpdatedAt = paymentstatusDescUpdatedAt.Default.(func() time.Time)
	// paymentstatus.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentstatus.UpdateDefaultUpdatedAt = paymentstatusDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentstatusDescID is the schema descriptor for id field.
	paymentstatusDescID := paymentstatusFields[0].Descriptor()
	// paymentstatus.DefaultID holds the default value on creation for the id field.
	paymentstatus.DefaultID = paymentstatusDescID.Default.(func() uuid.UUID)
}
