basePath: /
definitions:
  dto.DebtRequest:
    properties:
      amount:
        type: string
      invoice_id:
        type: string
      purchase_date:
        type: string
      title:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      details:
        type: string
      message:
        type: string
    type: object
  models.Debt:
    properties:
      amount:
        type: number
      category_id:
        type: string
      created_at:
        type: string
      due_date:
        type: string
      id:
        type: string
      invoice_id:
        type: string
      purchase_date:
        type: string
      status_id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta é a documentação da API
  title: API GO
  version: "1.0"
paths:
  /api/debts:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de débitos com paginação
      parameters:
      - description: Número da página
        in: query
        name: page
        type: integer
      - description: Tamanho da página
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Debt'
            type: array
        "400":
          description: Parâmetros inválidos
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro ao buscar dívidas
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Listar todos os débitos
      tags:
      - Débitos
    post:
      consumes:
      - application/json
      description: Cria um novo débito com os dados fornecidos no corpo da requisição
      parameters:
      - description: Dados do débito
        in: body
        name: debt
        required: true
        schema:
          $ref: '#/definitions/dto.DebtRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Debt'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro ao salvar o débito
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Criar um novo débito
      tags:
      - Débitos
  /api/debts/{id}:
    delete:
      consumes:
      - application/json
      description: Remove um débito pelo ID fornecido
      parameters:
      - description: ID do débito
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Débito deletado com sucesso
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Débito não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro ao deletar o débito
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Deletar um débito
      tags:
      - Débitos
    get:
      consumes:
      - application/json
      description: Retorna um débito pelo ID fornecido na URL
      parameters:
      - description: ID do débito
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Debt'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Débito não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro ao buscar o débito
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Buscar débito por ID
      tags:
      - Débitos
    put:
      consumes:
      - application/json
      description: Atualiza um débito existente com os novos dados fornecidos no corpo
        da requisição
      parameters:
      - description: ID do débito
        in: path
        name: id
        required: true
        type: string
      - description: Dados do débito
        in: body
        name: debt
        required: true
        schema:
          $ref: '#/definitions/dto.DebtRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Debt'
        "400":
          description: Requisição inválida ou ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Débito não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro ao atualizar o débito
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Atualizar um débito
      tags:
      - Débitos
schemes:
- http
swagger: "2.0"
