basePath: /api/v1
definitions:
  dto.DebtRequest:
    properties:
      amount:
        type: string
      due_date:
        type: string
      invoice_id:
        type: string
      purchase_date:
        type: string
      title:
        type: string
    type: object
  dto.DebtResponse:
    properties:
      amount:
        description: Valor do débito
        type: number
      category:
        description: Nome da categoria
        type: string
      category_id:
        description: ID da categoria
        type: string
      created_at:
        description: Data de criação do débito
        type: string
      due_date:
        description: Data de vencimento no formato YYYY-MM-DD
        type: string
      id:
        description: ID único do débito
        type: string
      invoice_title:
        description: Título da fatura associada
        type: string
      purchase_date:
        description: Data da compra no formato YYYY-MM-DD
        type: string
      status:
        description: Nome do status
        type: string
      status_id:
        description: ID do status
        type: string
      title:
        description: Título do débito
        type: string
      updated_at:
        description: Data da última atualização do débito
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      details:
        type: string
      message:
        type: string
    type: object
  dto.InvoiceRequest:
    properties:
      amount:
        type: string
      due_date:
        type: string
      issue_date:
        type: string
      title:
        type: string
    type: object
  dto.InvoiceResponse:
    properties:
      amount:
        description: Valor da fatura
        type: number
      created_at:
        description: Data de criação da fatura
        type: string
      due_date:
        description: Data de vencimento no formato YYYY-MM-DD
        type: string
      id:
        description: ID único da fatura
        type: string
      issue_date:
        description: Data de emissão no formato YYYY-MM-DD
        type: string
      status:
        description: Nome do status
        type: string
      status_id:
        description: ID do status
        type: string
      title:
        description: Título da fatura
        type: string
      updated_at:
        description: Data da última atualização da fatura
        type: string
    type: object
  models.Debt:
    properties:
      amount:
        type: number
      category_id:
        type: string
      created_at:
        type: string
      due_date:
        type: string
      id:
        type: string
      invoice_id:
        type: string
      purchase_date:
        type: string
      status_id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.Invoice:
    properties:
      amount:
        type: number
      created_at:
        type: string
      due_date:
        type: string
      id:
        type: string
      issue_date:
        type: string
      status_id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta API é projetada para monitoramento de dívidas, ajudando a organizar
    financeiramente.
  title: API GO
  version: "1.0"
paths:
  /debts:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de débitos com paginação e filtros opcionais
      parameters:
      - description: Filtrar por título do débito
        in: query
        name: title
        type: string
      - description: Filtrar por ID da categoria (UUID)
        in: query
        name: category_id
        type: string
      - description: Filtrar por ID do status (UUID)
        in: query
        name: status_id
        type: string
      - description: Valor mínimo do débito
        in: query
        name: min_amount
        type: number
      - description: Valor máximo do débito
        in: query
        name: max_amount
        type: number
      - description: Filtrar por data de início (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: Filtrar por data de término (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      - description: Filtrar por ID da fatura (UUID)
        in: query
        name: invoice_id
        type: string
      - description: Número da página
        in: query
        name: page
        type: integer
      - description: Tamanho da página
        in: query
        name: page_size
        type: integer
      - description: 'Ordenação dos resultados (ex: amount, due_date)'
        in: query
        name: order_by
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de débitos
          schema:
            items:
              $ref: '#/definitions/dto.DebtResponse'
            type: array
        "400":
          description: Parâmetros inválidos
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Listar todos os débitos
      tags:
      - Débitos
    post:
      consumes:
      - application/json
      description: Cria um novo débito com os dados fornecidos no corpo da requisição
      parameters:
      - description: Dados do débito
        in: body
        name: debt
        required: true
        schema:
          $ref: '#/definitions/dto.DebtRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Debt'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Criar um novo débito
      tags:
      - Débitos
  /debts/{id}:
    delete:
      consumes:
      - application/json
      description: Remove um débito pelo ID fornecido
      parameters:
      - description: ID do débito
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Registro deletado com sucesso
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Registro não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Deletar um débito
      tags:
      - Débitos
    get:
      consumes:
      - application/json
      description: Retorna um débito pelo ID fornecido na URL
      parameters:
      - description: ID do débito
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Debt'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Registro não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Buscar débito por ID
      tags:
      - Débitos
    put:
      consumes:
      - application/json
      description: Atualiza um débito existente com os novos dados fornecidos no corpo
        da requisição
      parameters:
      - description: ID do débito
        in: path
        name: id
        required: true
        type: string
      - description: Dados do débito
        in: body
        name: debt
        required: true
        schema:
          $ref: '#/definitions/dto.DebtRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Debt'
        "400":
          description: Requisição inválida ou ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Registro não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Atualizar um débito
      tags:
      - Débitos
  /invoices:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de faturas com filtros opcionais
      parameters:
      - description: Título da fatura
        in: query
        name: title
        type: string
      - description: ID do status da fatura (UUID)
        in: query
        name: status_id
        type: string
      - description: Valor mínimo da fatura
        in: query
        name: min_amount
        type: number
      - description: Valor máximo da fatura
        in: query
        name: max_amount
        type: number
      - description: Data inicial para filtrar (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: Data final para filtrar (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      - description: Número da página
        in: query
        name: page
        type: integer
      - description: Tamanho da página
        in: query
        name: page_size
        type: integer
      - description: 'Campo de ordenação (ex: title, amount)'
        in: query
        name: order_by
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de faturas
          schema:
            items:
              $ref: '#/definitions/dto.InvoiceResponse'
            type: array
        "400":
          description: Parâmetros inválidos
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Listar faturas
      tags:
      - Faturas
    post:
      consumes:
      - application/json
      description: Cria uma nova fatura com os dados fornecidos no corpo da requisição
      parameters:
      - description: Dados da fatura
        in: body
        name: invoice
        required: true
        schema:
          $ref: '#/definitions/dto.InvoiceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Invoice'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Criar uma nova fatura
      tags:
      - Faturas
  /invoices/{id}:
    delete:
      consumes:
      - application/json
      description: Remove uma fatura pelo ID fornecido
      parameters:
      - description: ID da fatura
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Registro deletado com sucesso
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Registro não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Deletar uma fatura
      tags:
      - Faturas
    get:
      consumes:
      - application/json
      description: Retorna uma fatura pelo ID fornecido na URL
      parameters:
      - description: ID da fatura
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Invoice'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Registro não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Buscar fatura por ID
      tags:
      - Faturas
    put:
      consumes:
      - application/json
      description: Atualiza uma fatura existente com os novos dados fornecidos no
        corpo da requisição
      parameters:
      - description: ID da fatura
        in: path
        name: id
        required: true
        type: string
      - description: Dados da fatura
        in: body
        name: invoice
        required: true
        schema:
          $ref: '#/definitions/dto.InvoiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Invoice'
        "400":
          description: Requisição inválida ou ID inválido
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Registro não encontrado
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Atualizar uma fatura
      tags:
      - Faturas
schemes:
- http
swagger: "2.0"
